# app/production/docker-compose.yml

version: "3.9"

services:
  backend:
    build:
      context: ../..
      dockerfile: app/production/Dockerfile
    container_name: ai_lifeos_backend
    restart: always
    env_file:
      - app/production/.env.production
    depends_on:
      - mongodb
      - redis
    ports:
      - "8000:8000"
    networks:
      - ai_net

  mongodb:
    image: mongo:6.0
    container_name: ai_lifeos_mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - ai_net

  redis:
    image: redis:7
    container_name: ai_lifeos_redis
    restart: always
    networks:
      - ai_net

  nginx:
    image: nginx:latest
    container_name: ai_lifeos_nginx
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - ai_net

volumes:
  mongo_data:

networks:
  ai_net:
    driver: bridge
